# Generated by Django 5.2.7 on 2025-10-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_Section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
